---
title: "Introduction"
output: pdf_document
pandoc_args: [
      "-V", "classoption=twocolumn"
    ]
---

*Range extremes and community ecology*   
	Range edges have long been of interest in the discipline of community ecology.  In particular, studies into range limits have come to the foreground in attempts to understand how these ranges might shift with changes in climate. Scientists have long observed the presence of species across an area, and a petering out of species at latitudinal range limits. Seminal works have theorized about the different causes underlying the filtering out of a species at its range limit (Darwin 1859). A fundamental tenet of community ecology is to determine the rules by which a community assembles. Community assembly is an ecological sorting process that filters out some species but allows others to survive (Ackerly 2003). Two general processes have been proposed for community assembly: (1) habitat filtering that limits species’ life strategies, and (2) resource partitioning that limits similarity in co-occurring species (Cornwell and Ackerly 2009). Studies into species distributions aim to shed light on what factors specifically might cause the limitations of a species as a way to more fully understand the rules dictating community assembly.  
In Hutchinsonian niche space, there are two types of niche. The fundamental niche, acknowledges the environment a species may tolerate, while the realized niche describes the performance of a species in the presence of competitors. The final distribution of a species and its community composition is the result of interplays between a combination of abiotic (i.e. environmental) and biotic (e.g. competition) factors (Ackerly 2003). More specifically, the two limitations imposed on species in determining their ranges are theorized as (1) abiotically stressful environments that limit species at high latitudes and altitudes and (2) species interactions that further impose restrictions on the species through competition (Louthan et. al, 2015; Pigot & Tobias, 2013). On the edges of its range, a species sees either biotic and/or abiotic factors forcing it out in a process called habitat filtering (Weiher & Keddy 1998). A species’ range is thus the spatial representation of its realized niche. Range limits are then predetermined by a species’ environment and the strength of its surrounding biotic factors (Pigot & Tobias 2013; Sexton et. al 2009).  
It is currently uncertain to what extent range limits are caused by biotic versus abiotic factors (Sexton et. al 2009). Darwin long ago theorized that abiotic factors constrain species at high latitudes, high elevation, and likewise environmentally stressful areas. Meanwhile, species interactions limit species in less stressful environments (Louthan et. al 2015). Yet there is much variation across species. It is likely that this variation is due to different dispersal capabilities, competition, and freezing tolerance (Louthan et. al 2015). Even so, there is a dearth of research looking at both biotic and abiotic factors. Many studies focus on one or the other, rarely examining both in conjunction with each other (Sexton et. al 2009). Examining a species at its range edge compared to its range interior, taking note of both the competitive niche it occupies and the environment the species lives in, thus provides important information on the interplay of factors limiting it. In all, examining a species at its range limit and range interior provides both information on the current preferred environment of that species and/or its realized niche, as well as its potential for adaptation given a changing environment.  


*Functional traits and niche differentiation*
To more fully understand the resource partitioning within niches in plants, it has become common practice to use functional traits as a proxy for understanding possible life strategies of different species. Functional traits have become a useful tool in understanding the nature of the relationship between plants within their communities, as well as understanding the relationship between environment and community assembly. Recent evidence has led to a shift away from the neutral model theory of general assembly (Hubbell 2001) towards the niche differentiation model (Kraft 2008). These studies have seen subtle differences in strategy differentiation contributing to species coexistence. Additionally, a large amount of intraspecific variation in functional traits may reduce the limiting effect of phylogenetic relatedness in nearby species (i.e. limiting similarity) (Burns & Strauss 2012). Functional traits have also been shown to be accurate predictors of species’ geographic ranges (Stahl & Wirth 2014), lending credence to the theory of niche differentiation and resource partitioning as a primary factor in determining a species’ geographic range.  
Different functional traits correspond to varying plant life strategies. Taking note of specific leaf area (SLA) serves as a proxy for life history, while leaf shape exhibits strong latitudinal and climate gradients for some species. The nutrients of tissues in plants also serve to provide information on resource investment. The ratio of carbon to nitrogen in a leaf gives information on the life history strategy of the leaf, as well as relative investment in the structures of the plant that harvest light. The height of a plant is an indicator of its local performance, while stem specific density provides insight into drought resistance and/or growth rate. By using related functional traits to describe a plant’s resource partitioning across its geographic range, I can more accurately predict how a species could respond to shifts in climate. Incorporating trait-based models in our understanding of the roles that species interactions play in community assembly is crucial (Pigot & Tobias 2013).

*Range shifts and response to climate change*
	Observing a species at its range edge can serve to test the conditions by which some populations adapt successfully (or not) to novel conditions. Due to global climate change, many species’ optimum environments are shifting north or up. However, species ranges are very mobile, often contracting or expanding over time (Brown, Stevens & Kaufman 1996; Davis & Shaw 2001). As the temperature increased late in the last glacial interval, woody species populations established themselves at increasingly higher latitudes in “migrations” (David & Shaw 2001).  
	Based on the niche conservatism hypothesis, when environmental conditions stretch beyond a species’ physiological tolerances, that species will either shift their distribution or face extinction (Peterson, Soberón, & Sánchez-Cordero 1999). More specifically, in response to a changing environment, a population may respond one of a few ways: 1) local population changes in microhabitat or altitudinal distribution; 2) large-scale shifts in geographic distribution, consisting of range expansions and range contraction in the former range; 3) adaptive evolution of the niche in response to the new conditions; and 4) extinction (Ackerly 2003; Thomas, Franco & Hill 2006). Historically, there is evidence that plant species underwent local adaptation (genetic) in response to changing climates, in addition to shifts in distribution (Davis & Shaw 2001). Yet populations are unlikely to undergo local adaptation at the pace necessary to match invasion of competitors from adjacent positions (Ackerly 2003). Additionally, competition has been shown to hinder the advancement of colonists into new environments during shifts due to changing environments (Suttle, Thomsen & Power 2001; Urban et. al 2012). This limits a species’ options in terms of biotic factors. Simultaneously, the speed of climate change affects how prevalent adaptive responses are (Ackerly 2003). Species are left with only one option: to migrate.  
	Indeed, range shifts for many species have been observed in response to increasing temperature over time (Chen et. al 2011). The observed pattern is upward, to higher latitudes and elevations as populations track their preferred environments (Sexton et. al 2009; Ackerly 2003; Parmesan 2006). Past studies have examined the effect of range limits and changing mean annual temperatures on woody plants, seeing a noticeable expansion north past the original northern range limits (Matías & Jump 2015). Simultaneously, species are faced with extinction on their southern range edges. In a study observing the distributional shifts of Silene acaulis (moss campion) and the geophyte Polygonum viviparum (alpine bistort) across six years, both populations saw die-out at their southern range edge (Doak & Morris 2010). At their northern edges, species may still face problems as well. In a meta-analysis of plant distributions spanning 40 years, Bertrand et. al (2011) found a lag in the responses of herbaceous forest species to climate change. Because edge populations may see more variability in survival and reproduction due to the frequency at which they must respond to limiting factors (Sexton et. al 2011), range extremes are a unique opportunity to understand current modes of community assembly, as well as to predict species’ future responses to climate change.  

*Latitudinal gradients as nature’s laboratory*
	 Recording a species’ functional traits and community composition across a latitudinal gradient provides a proxy for understanding how that species will respond to warming temperatures in its range exterior. Using a latitudinal gradient as a study system allows for observations of a species across a larger spatial scale than in warming facilities, and provides a much more accurate representation of the habitat that either allows or prevents a species from establishing itself (De Frenne et. al 2013). Many recent studies use altitudinal gradients as a predictor of species’ responses to climate change in lieu of latitudinal gradients, likely due to the relative ease of collection relative to sampling across latitudes (Matías & Jump 2015). Yet altitudinal gradients have a much smaller rate of spatial change in temperature as compared to latitudinal gradients (Jump, Matias & Peñuelas 2009). This further increases the chances that local adaptation will successfully occur due to genetic drift (Davis & Shaw 2001). On average, temperature decreases approaching the poles on the order of -.73 C per degree latitude in the Northern hemisphere. Other climatic variables, such as precipitation, also change across latitudes (De Frenne et. al 2013). Latitudinal gradients are thus an apt study system with which to integrate species interactions and environmental stressors as predictors of a species’ future distributions with regards to climate change.  

*Predictions and hypotheses*
To determine the nature of woody species’ future responses to climate change, I sampled six species of woody deciduous trees across four different sites on a latitudinal gradient in the northeastern United States and into Quebec. I predicted that:
H1: a species would become less competitive as they approached their latitudinal and climatic range limits, since populations at their geographic range edges more frequently experience strong, limiting factors (Sexton et. al 2009). 
A1: Alternatively, a species could grow more competitive as it approaches its range limit due to the presence of fewer competitors, thus leading to a greater realized niche. 
A2: Finally, it is a possibility that competition is not predicted by position in its climatic or latitudinal range, indicating that local factors might matter more within each population. Similarly, other factors could determine competitiveness, such as community composition and local adaptation, rather than a species’ position within its range limit. It is possible that a local community composition around each tree is most predictive of its competitive success, with little overall pattern across the latitudinal gradient.
Looking at a woody species’ competitiveness across a latitudinal gradient provides information into the part that biotic factors play in its realized niche, and the possible effects of those biotic factors in a warming environment. Since species often track their optimal environment (Ackerly 2003), strong limiting factors due to competitiveness may indicate that a species will not be able to migrate at a rate sufficient to account for population loss at their southern range edge.
H2: I also predicted that trees at their range extremes exhibit altered suites of functional traits from trees in the range interior (Weiher & Keddy 1998). Similar to the prediction (H1) above, because populations at their range limits often see more extreme environments, I predicted that their functional traits would altered plasticity compared to functional traits of individuals at their range interiors. Studies have shown that a species’ functional traits that are linked to life strategies vary based on the latitude of their origin (Cavender-Bares 2007).
	A1: Increases in intraspecific trait variation across a latitudinal gradient at the range limit would indicate increased genetic adaptation and/or increased plasticity. Since populations at their range extremes (and at more northern latitudes) face harsher environments than populations in their range interior, this could be due to a plant’s attempts to limit its phylogenetic similarity in the face of competitors in a sub-optimal environment, or simply because it is exhibiting greater plasticity in response to the more extreme environment.
	A2: On the other hand, decreased intraspecific trait variation approaching a range limit would indicate that only one combination of traits is successful in that particular limiting environment (Burns & Straus 2012).
	A3: Finally, no clear pattern in intra-specific variation in functional traits approaching the range limit of a species would indicate that other rules of community assembly are playing a larger part in the determining of range limits, such as competition or other biotic factors.
By examining community composition of certain woody species in conjunction with their corresponding functional traits across this latitudinal gradient, we can better predict how species composition will change at the forest level. In looking at both the community composition of species at these sites and their functional traits specifically at the range limits, we can understand which species are most at risk with the changing environment, and why they might not survive.

